apiVersion: apps/v1
kind: Deployment
metadata:
  name: glab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: glab
  template:
    metadata:
      labels:
        app: glab
    spec:
      containers:
        - name: glab
          image: hyunghki/demoglab
          ports:
            - containerPort: 80
              name: glab
