
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "hyunghkiS" do |server|
    server.vm.hostname = "hyunghkiS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "hyunghkiS"
      vb.memory = "8192"
      vb.cpus = 5
    end

    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - server --node-external-ip 192.168.56.110
      sudo chmod 664 /etc/rancher/k3s/k3s.yaml
      K3S_TOKEN=$(sudo cat /var/lib/rancher/k3s/server/node-token)
      echo $K3S_TOKEN > /vagrant/k3s_token
    SHELL
  end

  config.vm.define "hyunghkiSW" do |serverworker|
    serverworker.vm.hostname = "hyunghkiSW"
    serverworker.vm.network "private_network", ip: "192.168.56.111"

    serverworker.vm.provider "virtualbox" do |vb|
      vb.name = "hyunghkiSW"
      vb.memory = "8192"
      vb.cpus = 5
    end

    serverworker.vm.provision "shell", inline: <<-SHELL
      K3S_TOKEN=$(cat /vagrant/k3s_token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$K3S_TOKEN sh -
    SHELL
  end
end
