Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202404.26.0"

  config.vm.define "hyunghkiS" do |control|
    control.vm.hostname = "hyunghkiS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "hyunghkiS"]
      v.memory = "1024"
      v.cpus = "1"
    end
    # just for evaluation
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y net-tools
    SHELL
    control.vm.provision "shell", path: "scripts/server.sh"
  end
  config.vm.define "hyunghkiSW" do |control|
    control.vm.hostname = "hyunghkiSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "hyunghkiSW"]
      v.memory = "1024"
      v.cpus = "1"
    end
    # just for evaluation
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y net-tools
    SHELL
    control.vm.provision "shell", path: "scripts/agent.sh"
  end
end
