apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bonus-route
  namespace: gitlab
spec:
  entryPoints:
    - glab
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: glab
          port: 9999
